;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        backward-sentence
        dabbrev-expand
        evil-backward-char
        evil-change
        evil-delete
        evil-delete-backward-char-and-join
        evil-ex
        evil-force-normal-state
        evil-forward-char
        evil-insert
        evil-normal-state
        evil-yank
        kill-region
        org-backward-sentence
        org-beginning-of-line
        org-ctrl-c-ctrl-c
        org-delete-char
        org-end-of-line
        org-return-indent
        org-self-insert-command
        org-shifttab
        yaml-electric-backspace
        ))

(setq mc/cmds-to-run-once
      '(
        end-of-buffer
        evil-next-line
        evil-previous-line
        forward-sentence
        ido-switch-buffer
        mark-whole-buffer
        org-cycle
        org-force-self-insert
        org-kill-line
        org-mark-element
        set-fill-column
        upcase-region
        ))
